sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3308
    database: sky_take_out
    username: root
    password: 351558
  alioss:
    bucket-name: sky-luka
    access-key-secret: lm6F6EuhWq1PmEgasyUvc89gUAGFT0
    access-key-id: LTAI5tJw1LXQuTJhrTeUuhrH
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: "123456"
    database: 10